# Use root/example as user/password credentials
version: '3.1'

services:
  host_1:
    image: debian
    command: tail -f /var/log/faillog
    build: './host_1'
    volumes:
      - ./host_1/resolv.conf:/etc/resolv.conf
      - ./host_1/named.conf.local:/etc/bind/named.conf.local
      - ./host_1/named.conf.options:/etc/bind/named.conf.options
      - ./host_1/zone1.local.db:/etc/bind/zone1.local.db
      - ./host_1/zone3.local.db:/etc/bind/zone3.local.db
      - ./host_1/0.168.192.in-addr.arpa.db:/etc/bind/0.168.192.in-addr.arpa.db
      - ./host_1/libnss-ldap.conf:/etc/libnss-ldap.conf
      - ./host_1/nsswitch.conf:/etc/nsswitch.conf
      - ./host_1/add_group.ldif:/tmp/add_group.ldif
      - ./host_1/add_user.ldif:/tmp/add_user.ldif
    dns:
      - 192.168.0.20
      - 2001:3200:3100::20
    networks:
      local:
        ipv4_address: 192.168.0.10
        ipv6_address: 2001:3200:3100::10

  host_2:
    image: debian
    command: tail -f /var/log/faillog
    build: './host_2'
    volumes:
      - ./host_2/resolv.conf:/etc/resolv.conf
      - ./host_2/named.conf.local:/etc/bind/named.conf.local
      - ./host_2/named.conf.options:/etc/bind/named.conf.options
      - ./host_2/zone2.local.db:/etc/bind/zone2.local.db
      - ./host_2/zone3.local.db:/etc/bind/zone3.local.db
      - ./host_2/xn--80aaakzv5abgkcm.xn--90aenc5bjg.local.db:/etc/bind/xn--80aaakzv5abgkcm.xn--90aenc5bjg.local.db
      - ./host_2/0.0.0.0.0.0.1.3.0.0.2.3.1.0.0.2.ip6.arpa.db:/etc/bind/0.0.0.0.0.0.1.3.0.0.2.3.1.0.0.2.ip6.arpa.db
      - ./host_2/libnss-ldap.conf:/etc/libnss-ldap.conf
      - ./host_2/nsswitch.conf:/etc/nsswitch.conf
      - ./host_2/pam_ldap.conf:/etc/pam_ldap.conf
    dns:
      - 192.168.0.10
      - 2001:3200:3100::10
    networks:
      local:
        ipv4_address: 192.168.0.20
        ipv6_address: 2001:3200:3100::20

  host_3:
    image: debian
    command: tail -f /var/log/faillog
    networks:
      local:
        ipv4_address: 192.168.0.30
        ipv6_address: 2001:3200:3100::30
      inner:
        ipv4_address: 192.168.1.10
        ipv6_address: 2001:3200:3200::10

  host_4:
    image: debian
    command: tail -f /var/log/faillog
    networks:
      local:
        ipv4_address: 192.168.0.40
        ipv6_address: 2001:3200:3100::40
      inner:
        ipv4_address: 192.168.1.20
        ipv6_address: 2001:3200:3200::20

networks:
  local:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
        - subnet: 2001:3200:3100::/64
          gateway: 2001:3200:3100::1
  inner:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1
