FROM debian

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    bind9 \
    bind9utils \
    bind9-doc \
    dnsutils \
    ssh \
    rsync \
    rsyslog \
    slapd \
    ldap-utils \
    libnss-ldap \
    libpam-ldap \
    nscd \
    ntp \
    ntpdate \
    vim
