# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './calculator.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 120, 351, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnCE_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnCE_2.setObjectName("btnCE_2")
        self.gridLayout_2.addWidget(self.btnCE_2, 0, 2, 1, 1)
        self.btn8_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn8_2.setObjectName("btn8_2")
        self.gridLayout_2.addWidget(self.btn8_2, 1, 2, 1, 1)
        self.btn7_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn7_2.setObjectName("btn7_2")
        self.gridLayout_2.addWidget(self.btn7_2, 1, 1, 1, 1)
        self.btn1_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn1_2.setObjectName("btn1_2")
        self.gridLayout_2.addWidget(self.btn1_2, 3, 1, 1, 1)
        self.btn3_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn3_2.setObjectName("btn3_2")
        self.gridLayout_2.addWidget(self.btn3_2, 3, 3, 1, 1)
        self.btn9_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn9_2.setObjectName("btn9_2")
        self.gridLayout_2.addWidget(self.btn9_2, 1, 3, 1, 1)
        self.btn2_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn2_2.setObjectName("btn2_2")
        self.gridLayout_2.addWidget(self.btn2_2, 3, 2, 1, 1)
        self.btn6_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn6_2.setObjectName("btn6_2")
        self.gridLayout_2.addWidget(self.btn6_2, 2, 3, 1, 1)
        self.btnBS_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBS_2.sizePolicy().hasHeightForWidth())
        self.btnBS_2.setSizePolicy(sizePolicy)
        self.btnBS_2.setObjectName("btnBS_2")
        self.gridLayout_2.addWidget(self.btnBS_2, 0, 1, 1, 1)
        self.btn5_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn5_2.setObjectName("btn5_2")
        self.gridLayout_2.addWidget(self.btn5_2, 2, 2, 1, 1)
        self.btn4_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn4_2.setObjectName("btn4_2")
        self.gridLayout_2.addWidget(self.btn4_2, 2, 1, 1, 1)
        self.btnC0_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnC0_2.setObjectName("btnC0_2")
        self.gridLayout_2.addWidget(self.btnC0_2, 0, 3, 1, 1)
        self.btn0_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn0_2.setObjectName("btn0_2")
        self.gridLayout_2.addWidget(self.btn0_2, 4, 1, 1, 1)
        self.btnSign_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSign_2.setObjectName("btnSign_2")
        self.gridLayout_2.addWidget(self.btnSign_2, 4, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 4, 3, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, -1, 351, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.gridLayout_3.addWidget(self.radioButton, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 0, 2, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 0, 1, 2)
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.gridLayout_3.addWidget(self.radioButton_2, 1, 2, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.gridLayout_3.addWidget(self.radioButton_3, 1, 1, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.gridLayout_3.addWidget(self.radioButton_4, 1, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 5, 0, 1, 4)
        self.btnResult_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnResult_2.setObjectName("btnResult_2")
        self.gridLayout_3.addWidget(self.btnResult_2, 4, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 22))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnCE_2.setText(_translate("MainWindow", "CE"))
        self.btn8_2.setText(_translate("MainWindow", "8"))
        self.btn7_2.setText(_translate("MainWindow", "7"))
        self.btn1_2.setText(_translate("MainWindow", "1"))
        self.btn3_2.setText(_translate("MainWindow", "3"))
        self.btn9_2.setText(_translate("MainWindow", "9"))
        self.btn2_2.setText(_translate("MainWindow", "2"))
        self.btn6_2.setText(_translate("MainWindow", "6"))
        self.btnBS_2.setText(_translate("MainWindow", "BackSpace"))
        self.btn5_2.setText(_translate("MainWindow", "5"))
        self.btn4_2.setText(_translate("MainWindow", "4"))
        self.btnC0_2.setText(_translate("MainWindow", "C"))
        self.btn0_2.setText(_translate("MainWindow", "0"))
        self.btnSign_2.setText(_translate("MainWindow", "+/-"))
        self.pushButton.setText(_translate("MainWindow", "/"))
        self.radioButton.setText(_translate("MainWindow", "/"))
        self.radioButton_2.setText(_translate("MainWindow", "-"))
        self.radioButton_3.setText(_translate("MainWindow", "*"))
        self.radioButton_4.setText(_translate("MainWindow", "+"))
        self.btnResult_2.setText(_translate("MainWindow", "="))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
