# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './calculator.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 120, 351, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnCE = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnCE.setObjectName("btnCE")
        self.gridLayout.addWidget(self.btnCE, 0, 2, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn8.setObjectName("btn8")
        self.gridLayout.addWidget(self.btn8, 1, 2, 1, 1)
        self.btn7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn7.setObjectName("btn7")
        self.gridLayout.addWidget(self.btn7, 1, 1, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 3, 1, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 3, 3, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn9.setObjectName("btn9")
        self.gridLayout.addWidget(self.btn9, 1, 3, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 3, 2, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn6.setObjectName("btn6")
        self.gridLayout.addWidget(self.btn6, 2, 3, 1, 1)
        self.btnBS = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBS.sizePolicy().hasHeightForWidth())
        self.btnBS.setSizePolicy(sizePolicy)
        self.btnBS.setObjectName("btnBS")
        self.gridLayout.addWidget(self.btnBS, 0, 1, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn5.setObjectName("btn5")
        self.gridLayout.addWidget(self.btn5, 2, 2, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn4.setObjectName("btn4")
        self.gridLayout.addWidget(self.btn4, 2, 1, 1, 1)
        self.btnC0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnC0.setObjectName("btnC0")
        self.gridLayout.addWidget(self.btnC0, 0, 3, 1, 1)
        self.btn0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn0.setObjectName("btn0")
        self.gridLayout.addWidget(self.btn0, 4, 1, 1, 1)
        self.btnSign = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSign.setObjectName("btnSign")
        self.gridLayout.addWidget(self.btnSign, 4, 2, 1, 1)
        self.btnSlash = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSlash.setObjectName("btnSlash")
        self.gridLayout.addWidget(self.btnSlash, 4, 3, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, -1, 351, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioDiv = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioDiv.setObjectName("radioDiv")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioDiv)
        self.gridLayout_2.addWidget(self.radioDiv, 1, 0, 1, 1)
        self.lineEdit_second = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_second.setObjectName("lineEdit_second")
        self.gridLayout_2.addWidget(self.lineEdit_second, 0, 2, 1, 2)
        self.lineEdit_first = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_first.setObjectName("lineEdit_first")
        self.gridLayout_2.addWidget(self.lineEdit_first, 0, 0, 1, 2)
        self.radioSub = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioSub.setObjectName("radioSub")
        self.buttonGroup.addButton(self.radioSub)
        self.gridLayout_2.addWidget(self.radioSub, 1, 2, 1, 1)
        self.radioMul = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioMul.setObjectName("radioMul")
        self.buttonGroup.addButton(self.radioMul)
        self.gridLayout_2.addWidget(self.radioMul, 1, 1, 1, 1)
        self.radioAdd = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioAdd.setChecked(True)
        self.radioAdd.setObjectName("radioAdd")
        self.buttonGroup.addButton(self.radioAdd)
        self.gridLayout_2.addWidget(self.radioAdd, 1, 3, 1, 1)
        self.lineEdit_result = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.gridLayout_2.addWidget(self.lineEdit_result, 5, 0, 1, 4)
        self.btnResult = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnResult.setObjectName("btnResult")
        self.gridLayout_2.addWidget(self.btnResult, 4, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 22))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnCE.setText(_translate("MainWindow", "CE"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btnBS.setText(_translate("MainWindow", "BackSpace"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btnC0.setText(_translate("MainWindow", "C"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btnSign.setText(_translate("MainWindow", "+/-"))
        self.btnSlash.setText(_translate("MainWindow", "/"))
        self.radioDiv.setText(_translate("MainWindow", "/"))
        self.radioSub.setText(_translate("MainWindow", "-"))
        self.radioMul.setText(_translate("MainWindow", "*"))
        self.radioAdd.setText(_translate("MainWindow", "+"))
        self.btnResult.setText(_translate("MainWindow", "="))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
